version: "3.8"
services:
  groovy-app:
   build: .
   image: priyeshdutta/devops-groovy-app-spring
   volumes: 
   - app-data:/var/bin
   ports:
   - 5000:8888
  mongodb:
   image: mongo:6-jammy
   ports: 
   - 27017:27017
   volumes:
   - app-data:/data/db 	
volumes:
 app-data: