
apiVersion: v1
kind: Service
metadata:
  name: devops-groovy-app-service
spec:
  selector:
    app: devops-groovy-app
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
