pipeline {
agent any

tools {
// Install the Maven version configured as "M3" and add it to the path.
maven "mvn"
}

stages {
stage('Build') {
steps {
// Get some code from a GitHub repository
git 'https://github.com/Ankit-0212/devops-spring-groovy-pipeline.git&#39;

script{
               if(isUnix()){
// Run Maven on a Unix agent.
sh "mvn -Dmaven.test.failure.ignore=true clean package"
               }
               else{
// To run Maven on a Windows agent, use
bat "mvn -Dmaven.test.failure.ignore=true clean package"
}
}
}
stage('Integration Test') {
steps {

script{
               if(isUnix()){
sh "mvn -Dmaven.test.failure.ignore=true clean verify"
               }
               else{
bat "mvn -Dmaven.test.failure.ignore=true clean verify"
}
}
}

post {
// If Maven was able to run the tests, even if some of the test
// failed, record the test results and archive the jar file.
success {
junit '**/target/surefire-reports/TEST-*.xml'
archiveArtifacts 'target/*.jar'
}
}
}
}
}